spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://39.107.76.162:3306/zhangchi?useSSL=false
    username: zhangchi
    password: zhangchi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



files:
  imgs:
    patch: D:/test/
    get: file:///D:/test/

